const cars = {
    Abay: [
        "A13"
    ],
    Abarth: [
        "124 Spider"
    ],
    Acura: [
        "MDX",
        "NSX",
        "RDX"
    ],
    AlfaRomeo: [
        "Guilia",
        "Stelvio",
        "Tonale"
    ],
    Ariel: [
        "Atom",
        "Nomad"
    ],
    AstonMartin: [
        "Cygnet",
        "DBX",
        "DBS"
    ],
    Audi: [
        "A1",
        "A2",
        "A3",
        "A4",
        "A5",
        "A6",
        "A7",
        "A8",
        "Cabriolet",
        "Coupe",
        "e-tron",
        "e-tron GT",
        "Q1",
        "Q2",
        "Q2L",
        "Q3",
        "Q4 e-torn",
        "Q5",
        "Q7",
        "Q8",
        "R8",
        "S1",
        "S2",
        "S3",
        "S4",
        "S5",
        "S6",
        "S7",
        "S8"
    ],
    Bentley: [
        "Bentayga",
        "Continental",
        "Flying spur"
    ],
    BMW: [
        "1 Series",
        "2 Series",
        "3 Series",
        "4 Series",
        "5 Series",
        "6 Series",
        "7 Series",
        "i3",
        "i8",
        "iX",
        "M1",
        "M2",
        "M3",
        "M4",
        "M5",
        "M6",
        "M8",
        "M850",
        "X1",
        "X2",
        "X3",
        "X4",
        "X5",
        "X6",
        "X7",
        "Z1",
        "Z3",
        "Z4",
        "Z8"
    ],
    Brabus: [
        "G700",
        "G800"
    ],
    Bugatti: [
        "Veyron",
        "Chiron"
    ],
    Buick: [
        "Cascada",
        "Century",
        "Electra",
        "Encore",
        "Envision",
        "Lacrosse",
        "Le Sabre",
        "Verano"
    ],
    BYD: [
        "G3",
        "G5",
        "G6",
        "Dolphin",
        "Flyer",
        "Song Max",
        "S6",
        "S7",
        "S8",
        "F3",
        "F3DM",
        "Tang",
        "iev4",
        "iev6",
        "Qin",
        "Atto 3",
        "e5",
        "Han",
        "L3"
    ],
    Cadillac: [
        "ATS",
        "CT4",
        "CT5",
        "CT6",
        "CTS",
        "Deville",
        "Eldorado",
        "Escalade",
        "XTS"
    ],
    Catherham: [
        "CSR 260",
        "Classic 7"
    ],
    Chevrolet: [
        "2500",
        "Astro",
        "Aveo",
        "Blazer",
        "Bolt",
        "Camaro",
        "Captiva",
        "Chevelle",
        "Cruze",
        "Corolado",
        "Corvette",
        "Equinox",
        "Impala",
        "Malibu",
        "Matiz",
        "Silverado",
        "Spark",
        "Tahoe",
        "Trailblazer"
    ],
    Chery: [
        "Arrizo",
        "Tiggo",
        "QQ"
    ],
    Chrysler: [
        "300 C"
    ],
    Citroen: [
        "DS3",
        "DS4",
        "DS5",
        "DS7",
        "C1",
        "C2",
        "C3",
        "C4",
        "C5",
        "C6",
        "C8"
    ],
    Corvette: [
        "C1",
        "C2",
        "C3",
        "C4",
        "C5",
        "C6",
        "C7",
        "C8",
        "Z06",
        "ZR1",
        "Stingray"
    ],
    Dacia: [
        "Duster",
        "Logan",
        "Sandro",
        "Spring"
    ],
    Daewoo: [
        "Damas",
        "Matiz",
        "Musso",
        "Rexton"
    ],
    DAF: [
        "400",
        "428",
        "435"
    ],
    Daihatsu: [
        "Sirion",
        "Terios"
    ],
    Datsun: [
        "240z"
    ],
    DFM: [
        "AX7",
        "E70",
        "Glory 330"
    ],
    Dodge: [
        "Challenger",
        "Charger",
        "Dakota",
        "Durango",
        "Viper"
    ],
    Faw: [
        "Bestune B70",
        "Bestune T55",
        "Bestune T77",
        "Bestune T99"
    ],
    Ferrari: [
        "Enzo",
        "LaFerrari"
    ],
    Fiat: [
        "124 Spider",
        "500",
        "Multipla",
        "Panda",
        "Punto",
        "Uno"
    ],
    Fisker: [
        "EMotion",
        "Karma",
        "Orbit"
    ],
    Ford: [
        "Aerostar",
        "Bronco",
        "Capri",
        "Crown",
        "Ecosport",
        "Edge",
        "Escape",
        "Escort",
        "Expedition",
        "Explorer",
        "F1",
        "F100",
        "F150",
        "F250",
        "F350",
        "F450",
        "F550",
        "F650",
        "F Super Duty",
        "Falcon",
        "Fiesta",
        "Focus",
        "Fusion",
        "Granada",
        "Kuma",
        "Maverick",
        "Mustang",
        "Mustang Mach-e",
        "Puma",
        "Ranger",
        "Ranger Raptor",
        "Scorpio",
        "Sierra",
        "Taunus",
        "Taurus",
        "Thunderbird",
        "Torino",
        "Transit"
    ],
    Foton: [
        "Gratour",
        "Toplander",
        "View Traveller",
        "View Transvan",
    ],
    Geely: [
            'GC7',
            'Addis',
            'Saba'
        ],
    Genesis: [
            'G70',
            'G80',
            'G90',
            'GV70',
            'GV80'
        ],
        Glory: [
            '330'
        ],
        GMC: [
            'Canyon',
            'Envoy',
            'Safari',
            'Savana',
            'Sierra',
            'Terrain',
            'Yukon'
        ],
    GreatWall: [
            'Hover'
        ],
    Haval: [
            'H2',
            'H6',
            'H9'
        ],
    Hino: [
            '600'
        ],
    Honda: [
            'Accord',
            'City',
            'Civic',
            'CR-V',
            'Crosstour',
            'Fit',
            'Integra',
            'Jazz',
            'NSX',
            'Odyssey',
            'Pilot',
            'Prelude',
            'Ridgeline',
            'S2000'
        ],
        Howo: [
            'Sinotruck'
        ],
        Hummer: [
            'H1',
            'H2',
            'H3',
            'HX',
            'EV'
        ],
        Hyundai: [
            'Accent',
            'Atop',
            'Avante',
            'Bayon',
            'Creta',
            'Elantra',
            'Genesis',
            'Getz',
            'Grandeur',
            'H100',
            'H200',
            'H300',
            'H350',
            'H-1',
            'i10',
            'i20',
            'i30',
            'Ioniq',
            'Ioniq 5',
            'Ioniq 6',
            'iX20',
            'iX35',
            'iX55',
            'Kona',
            'Next',
            'Pony',
            'Santa Fe',
            'Santamo',
            'Solaris',
            'Sonata',
            'Starex',
            'Staria',
            'Terracan',
            'Tucson',
            'Veloster'
        ],
        Infiniti: [
            'FX',
            'G25',
            'G35',
            'G37',
            'Q30',
            'Q45',
            'Q50',
            'Q60',
            'Q70',
            'Q80',
            'QX30',
            'QX50',
            'QX56',
            'QX60',
            'QX70',
            'QX80'
        ],
        Isuzu: [
            'CYZ',
            'D-Max',
            'FSR',
            'NKR',
            'NNR',
            'NPR',
            'Rodeo',
            'Trooper'
        ],
        Iveco: [
            'Campagnola',
            'Daily',
            'Massif'
        ],
        Jac: [
            'e-S2',
            'e-S4',
            'J7',
            'JS3',
            'JS4',
            'JS7'
        ],
        Jaguar: [
            '420',
            'D-Type',
            'Daimler',
            'E-Pace',
            'E-Type',
            'F-Pace',
            'F-Type',
            'I-Pace',
            'X-Type',
            'X300',
            'XE',
            'XF',
            'XJ',
            'XJ12',
            'XJ40',
            'XJ6',
            'XJ8',
            'XK8',
            'XKR'
        ],
        Jeep: [
            'Cherokee',
            'Compass',
            'Gladiator',
            'Grand Cherokee',
            'Liberty',
            'Patriot',
            'Renegade',
            'Wagoneer',
            'Wrangler'
        ],
        Jetour: [
            'X70',
            'X70 Plus',
            'X90 Plus'
        ],
        Kia: [
            'Carnival',
            'Ceed',
            'e-Niro',
            'EV6',
            'Mohave',
            'Optima',
            'Picanto',
            'Pride',
            'Rio',
            'Seltos',
            'Soul',
            'Soul EV',
            'Sorento',
            'Stonic'
        ],
        Koenigsegg: [
            'Agera',
            'Regera'
        ],
        KTM: [
            'X-Bow'
        ],
        Lada: [
            'Niva',
            'Riva',
            'Universal',
            'Urban'
        ],
        Lamborghini: [
            'Huracan',
            'Aventador'
        ],
        Lancia: [
            'Belta',
            'Delta',
            'Zeta'
        ],
        LandRover: [
            'Defender',
            'Discovery',
            'Freelander'
        ],
        Lexus: [
            'ES',
            'GS',
            'GX 460',
            'GX 470',
            'IS',
            'LC',
            'LFA',
            'LS',
            'LX450d',
            'LX470',
            'LX570',
            'NX',
            'RC',
            'RX',
            'SC',
            'UX'
        ],
        Lifan: [
            '320',
            '520',
            '530',
            '620',
            '720',
            'L7'
        ],
        Lincoln: [
            'Aviator',
            'Continental',
            'Navigator'
        ],
        Lotus: [
            'Cortina',
            'Elan',
            'Elise',
            'Elite',
            'Emira',
            'Exige',
            'Omega',
            'V8'
        ],
        Lucid: [
            'Air'
        ],
        Mahindra: [
            'Alturas',
            'Bolero',
            'CJ',
            'Genie',
            'Gota',
            'Jeep',
            'KUV100',
            'Marazzo',
            'Nuvosport',
            'Reva',
            'Scorpio',
            'Ther',
            'TUV300',
            'Verity',
            'XUV300',
            'XUV500',
            'Xylo'
        ],
        Maserati: [
            'GrandSport',
            'GrandTurismo',
            'Indy'
        ],
        Maybach: [
            '57',
            '62',
            'Pullman'
        ],
        McLaren: [
            'Senna',
            'P1',
            '720S'
        ],
        MercedesBenz: [
            'A-Class',
            'Actros',
            'B-Class',
            'C-Class',
            'Citan',
            'CL',
            'CLA',
            'CLC',
            'CLK',
            'CLS',
            'E-Class',
            'EQ',
            'EQS',
            'G-Class',
            'GL',
            'ML',
            'MB',
            'S-Class',
            'X 220',
            'X 250',
            'X 350'
        ],
        Mini: [
            'Cooper',
            'Clubman'
        ],
        Mitsubishi: [
            'Attrage',
            'Eclipse',
            'Eclipse Cross',
            'Galant',
            'L200',
            'L300',
            'L400',
            'Lancer',
            'Mini Pajero',
            'Mirage',
            'Montero',
            'Outlander',
            'Pajero',
            'Starion'
        ],
        Nio: [
            'EP9',
            'ES6',
            'ES7',
            'ES8',
            'Et7'
        ],
        Nissan: [
            '100 NX',
            '200 SX',
            '280 ZX',
            '300 ZX',
            '350 Z',
            '370 Z',
            'Almera',
            'Altima',
            'Ariya',
            'Armada',
            'Cargo',
            'Cherry',
            'Cube',
            'Datsun',
            'Frontier',
            'GT-R',
            'Juke',
            'Leaf',
            'Maxima',
            'Micro',
            'Murano',
            'Navara',
            'Note',
            'NP300',
            'NV200',
            'Pathfinder',
            'Patrol',
            'Qashqai',
            'Quest',
            'Rogue',
            'Safari',
            'Sentra',
            'Sunny',
            'Terrano',
            'Tida',
            'Titan',
            'X-Trail'
        ],
        Opel: [
            'Astra',
            'Calibra',
            'Campo',
            'Corsa',
            'Omega',
            'Tigra',
            'Vectra'
        ],
        Pagani: [
            'Huayra',
            'Zonda'
        ],
        Peugeot: [
            '1007',
            '104',
            '106',
            '107',
            '108',
            '2008',
            '204',
            '205',
            '206',
            '207',
            '208',
            '3008',
            '301',
            '304',
            '305',
            '306',
            '307',
            '308',
            '309',
            '4007',
            '4008',
            '404',
            '405',
            '406',
            '407',
            '5008',
            '504',
            '505',
            '508',
            '604',
            '605',
            '607',
            '806',
            '807',
            'Bopped',
            'Boxer',
            'Camper',
            'e-2008',
            'e-208',
            'Expert',
            'iOn',
            'J5',
            'J9',
            'Partner',
            'Ranch',
            'RCZ',
            'Ritter',
            'Traveller'
        ],
        Pontiac: [
            '6000',
            'Aztek',
            'Fiero',
            'Firebird',
            'G6',
            'GTO',
            'Montana',
            'Targa',
            'Vibe'
        ],
        Porsche: [
            '911',
            'Boxter',
            'Cayenne',
            'Cayman',
            'Macan',
            'Taycan'
        ],
        RAM: [
            '1500',
            '2500',
            '3500',
            'Promaster',
            'TRX'
        ],
        RangeRover: [
            'Evoque',
            'Sport',
            'Vogue'
        ],
        Renault: [
            'Captur',
            'Clio',
            'Duster',
            'Kangoo',
            'Logan',
            'Megane',
            'Sandro',
            'Twizy',
            'Zoe'
        ],
        'Rolls Royce': [
            'Phantom'
        ],
        Saab: [
            'GT-750',
            'Sonett'
        ],
        Scania: [
            'V8',
            'G-Series',
            'L-Series',
            'R-Series',
            'S-Series'
        ],
        Seat: [
            'Terra'
        ],
        Shelby: [
            'Baja Raptor',
            'Mustang GT500'
        ],
        Sino: [
            'Truck'
        ],
        Skoda: [
            'Fabia',
            'Kamiq',
            'Karoq',
            'Yeti'
        ],
        Smart: [
            'ForFour',
            'ForTwo',
            'Roadster'
        ],
        SsangYong: [
            'Actyon',
            'Family',
            'Korando',
            'Kyron',
            'MUSSO',
            'REXTON',
            'Rodius',
            'Tivoli',
            'XLV'
        ],
        Subaru: [
            'Ascent',
            'Baja',
            'BRZ',
            'Crosstrek',
            'Forester',
            'Impreza',
            'Legacy',
            'Outback',
            'WRX'
        ],
        Suzuki: [
            'Across',
            'Alto',
            'Baleno',
            'Carry',
            'Celario',
            'Dzire',
            'Grand Vitara',
            'Ignis',
            'Jimny',
            'Liana',
            'Samurai',
            'Swift',
            'SX4'
        ],
        Tata: [
            'Aria',
            'Bolt',
            'Estate',
            'Harrier',
            'Hexa',
            'Indica',
            'Indigo',
            'Nano',
            'Nexon',
            'Pickup',
            'Safari',
            'Sport',
            'Sumo',
            'Telcoline',
            'Telcosport',
            'Tiago',
            'Tigor',
            'Xenon',
            'Zest'
        ],
        Tesla: [
            'Cybertruck',
            'Model 3',
            'Model Y',
            'Model X',
            'Model S',
            'Roadster'
        ],
        Toyota: [
            '4 Runner',
            'Auris',
            'Avalon',
            'Avensis',
            'Aygo',
            'Bz4x',
            'C-HR',
            'Camry',
            'Carina',
            'Celica',
            'Coaster',
            'Corolla',
            'Corolla Cross',
            'Corolla Verso',
            'Corona',
            'Crown',
            'FJ Cruiser',
            'FJ40',
            'Fortuner',
            'Hiace',
            'Highlander',
            'Hilux',
            'IQ',
            'Land Cruiser',
            'Land Cruiser Prado',
            'Mark II',
            'Matrix',
            'Murai',
            'MR2',
            'Passo',
            'Platz',
            'Previa',
            'Prius',
            'Pro ace',
            'RAV4',
            'Sequoia',
            'Sienna',
            'Starlet',
            'Supra',
            'Tacoma',
            'Tercel',
            'Tundra',
            'Urban Cruiser',
            'Verso',
            'Vitz',
            'Yaris',
            'Yaris Belta'
        ],
        UD: [
            'Condor'
        ],
        Volkswagen: [
            'Amarok',
            'Arteon',
            'Atlas',
            'Beetle',
            'Caddy',
            'Fox',
            'Golf',
            'ID. 3',
            'ID. 4',
            'ID. 5',
            'ID. 6',
            'Jetta',
            'Passat',
            'Phaeton',
            'Polo',
            'T-Cross',
            'T5 Transporter',
            'Taigo',
            'Tiguan',
            'Touareg',
            'Up'
        ],
        Volvo: [
            '240',
            '244',
            '245',
            '262',
            '264',
            '265',
            '340',
            '360',
            '440',
            '460',
            '480',
            '740',
            '744',
            '745',
            '760',
            '764',
            '780',
            '850',
            '855',
            '940',
            '965',
            'Amazon',
            'C30',
            'C40',
            'C70',
            'P1800',
            'Polar',
            'S60',
            'S70',
            'S80',
            'S90',
            'V40',
            'V50',
            'V60',
            'V70',
            'V90',
            'XC40',
            'XC60',
            'XC70',
            'XC90'
        ],
        Weltmester: [
            'EX5-Z',
            'EX6 Plus',
            'W6'
        ],
        Wuling: [
            'Mini EV'
        ],
        Xpeng: [
            'G2',
            'P2',
            'P7'
        ],
        Zotye: [
            'E200',
            'T300',
            'T600',
            'T700',
            'Z100',
            'Z360',
            'Z700'
        ]
}

export default cars;